FROM python:3.12

# create workdir
RUN mkdir /admin_app

# set workdir
WORKDIR /admin_app

COPY requirements.txt .

RUN pip install -r requirements.txt

# copy all files
COPY . .

RUN chmod a+x bash_cmd/*.sh
#CMD gunicorn main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:5541
