# Докер файл, который запускает базу данных
# docker compose --env-file ../.env up

version: '3.9'
services:
  where_is_it_db:
    image: postgres:17-alpine
    container_name: where_is_it_db
    restart: unless-stopped
    volumes:
      - /var/lib/postgresql/data_where_is:/var/lib/postgresql/data_where_is
    env_file:
      - ../.env
    ports:
      - '${DB_OUT_PORT}:5432'

  where_is_redis_db:
    image: redis:7-alpine
    container_name: where_is_redis_db
    restart: unless-stopped
    ports:
      - "${REDIS_OUT_PORT}:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - ../.env


