"""add_exit_coord

Revision ID: 68cb01a7f96e
Revises: 69aabcf8d6ab
Create Date: 2025-06-09 17:45:20.110144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68cb01a7f96e'
down_revision: Union[str, None] = '69aabcf8d6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch_schemas_table', sa.Column('exit_x', sa.Integer(), nullable=False))
    op.add_column('branch_schemas_table', sa.Column('exit_y', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'branch_schemas_table', ['branch_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branch_schemas_table', type_='unique')
    op.drop_column('branch_schemas_table', 'exit_y')
    op.drop_column('branch_schemas_table', 'exit_x')
    # ### end Alembic commands ###
