"""nullable_branch_geo

Revision ID: 9937a7ad9f1d
Revises: 68cb01a7f96e
Create Date: 2025-06-12 20:07:13.177856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9937a7ad9f1d'
down_revision: Union[str, None] = '68cb01a7f96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_location_table', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('client_location_table_branch_id_fkey'), 'client_location_table', type_='foreignkey')
    op.create_foreign_key(None, 'client_location_table', 'branches_table', ['branch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_location_table', type_='foreignkey')
    op.create_foreign_key(op.f('client_location_table_branch_id_fkey'), 'client_location_table', 'branches_table', ['branch_id'], ['id'], ondelete='CASCADE')
    op.alter_column('client_location_table', 'branch_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
