"""add_organization_id

Revision ID: 390418e8a07d
Revises: 9937a7ad9f1d
Create Date: 2025-06-12 20:31:35.603625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '390418e8a07d'
down_revision: Union[str, None] = '9937a7ad9f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_location_table', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'client_location_table', 'organizations_table', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_location_table', type_='foreignkey')
    op.drop_column('client_location_table', 'organization_id')
    # ### end Alembic commands ###
